branches/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from tastypie.api import Api

from branches.views import *
from branches.api import *

v1_api = Api(api_name='v1')
v1_api.register(ServerResource())
v1_api.register(ProjectResource())
v1_api.register(RequestResource())

urlpatterns = patterns('',
    # API
    url(r'^api/', include(v1_api.urls)),

    # new project, server, etc...
    url(r'^projects/$', ProjectListView.as_view(), name='project-list'),
    url(r'^server/new/$', NewServerView.as_view(), name='new-server'),

    # projects
    url(r'^project/new/$', NewProjectView.as_view(), name='new-project'),
    url(r'^(?P<owner>[\w\-_]+)/$', ProjectListView.as_view(), name='owner-project-list'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/$', ProjectDetailView.as_view(), name='project-detail'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/edit/$', ProjectUpdateView.as_view(), name='project-edit'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/delete/$', ProjectDeleteView.as_view(), name='project-delete'),


    # Servers
    url(r'^(?P<owner>[\w\-_])+/(?P<project>[\w\-_]+)/(?P<server>[\w\-_]+)/$', ServerDetailView.as_view(), name='server-detail'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/(?P<server>[\w\-_]+)/initialize/$', InitializeServerView.as_view(), name='initialize-server'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/(?P<server>[\w\-_]+)/edit/$', ServerUpdateView.as_view(), name='server-edit'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/(?P<server>[\w\-_]+)/delete/$', ServerDeleteView.as_view(), name='server-delete'),
    url(r'^(?P<owner>[\w\-_]+)/(?P<project>[\w\-_]+)/(?P<server>[\w\-_]+)/initializing/$', ServerInitiailizingView.as_view(), name='server-initializing'),
    # url(r'^servers/$', ServerListView.as_view(), name='server-list'),
    # url(r'^server/(?P<pk>\d+)/log/$', ServerLogView.as_view(), name='server-log'),

    # # repositories
    # url(r'^repositories/$', RepositoryListView.as_view(), name='repository-list'),
    # url(r'^repositories/new/$', NewRepositoryView.as_view(), name='new-repository'),

    # # integrations
    url(r'^rackspace/connect/$', RackspaceConnectView.as_view(), name='rackspace-connect'),
    url(r'^rackspace/servers/$', RackspaceServerListView.as_view(), name='rackspace-server-list'),

    url(r'^digitalocean/connect/$', DigitalOceanConnectView.as_view(), name='digitalocean-connect'),
    url(r'^digitalocean/authorize/$', DigitalOceanAuthorizeView.as_view(), name='digitalocean-authorize'),
    url(r'^digitalocean/servers/$', DigitalOceanServerListView.as_view(), name='digitalocean-server-list'),
)

django_branches/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

from django_branches.views import (
    LoginView, LogoutView, HomeView, RegistrationView,
)


urlpatterns = patterns(
    '',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^docs/', include('docs.urls')),

    # Both urls needed for branches to work
    url(r'', include('branches.urls', namespace="branches")),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

branches/views.py
from datetime import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import FormView, RedirectView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from django.views.generic.detail import SingleObjectMixin
from django.conf import settings

import pyrax
from requests_oauthlib import OAuth2Session
import digitalocean

from .models import Server, Repository, copy_key_to_server, Project, UserProfile
from .forms import (
    NewServerForm, InitializeServerForm, NewProjectForm, NewRepositoryForm, 
    RackspaceConnectForm
)

class ServerListView(ListView):
    """ Lists all the servers the user has
    """ 

    model = Server

class RepositoryListView(ListView):

    model = Repository


class NewRepositoryView(CreateView):
    """ View for creating a new server
    """

    model = Repository
    form_class = NewRepositoryForm

    def get_success_url(self):
        return reverse("branches:repository-list")

class NewServerView(CreateView):
    """ View for creating a new server
    """

    model = Server
    form_class = NewServerForm

    def get_success_url(self):
        server = self.object
        project = server.project
        owner = project.owner.username
        return reverse(
            "branches:initialize-server", 
            kwargs=dict(
                server=server.slug, 
                project=project.slug,
                owner=owner))

    def get_form_kwargs(self):
        kwargs = super(NewServerView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_invalid(self, form):
        print("Errors in form")
        print(form.errors)
        return super(NewServerView, self).form_invalid(form)

    def form_valid(self, form):
        print("Processing form...")
        cleaned_data = form.cleaned_data
        project = cleaned_data.pop("project")
        owner = cleaned_data.pop("owner")
        location = cleaned_data.pop("location")
        server = form.save(commit=False)
        server.project = project
        server.owner = owner
        server.save()
        if not server.repository:
            server.repository = Repository.objects.create(location=location)
            server.save()
        else:
            repository = server.repository
            repository.location = location
            repository.save()
        self.object = server
        return redirect(self.get_success_url())


class ServerUpdateView(UpdateView):
    model = Server
    form_class = NewServerForm
    template_name = "branches/server_form.html"
    slug_field = "slug"
    slug_url_kwarg = "server"

    def get_form_kwargs(self):
        kwargs = super(ServerUpdateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        project = cleaned_data.pop("project")
        owner = cleaned_data.pop("owner")
        location = cleaned_data.pop("location")
        server = form.save(commit=False)
        server.project = project
        server.owner = owner
        server.save()
        if not server.repository:
            server.repository = Repository.objects.create(location=location)
            server.save()
        else:
            repository = server.repository
            repository.location = location
            repository.save()
        self.object = server
        return redirect(self.get_success_url())

class ServerDeleteView(DeleteView):
    model = Server
    template_name = "branches/server_delete.html"
    slug_field = "slug"
    slug_url_kwarg = "server"

    def get_form_kwargs(self):
        kwargs = super(ServerDeleteView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


    def get_success_url(self):
        return reverse("branches:server-list")

class InitializeServerView(FormView, SingleObjectMixin):

    model = Server
    form_class = InitializeServerForm
    template_name = "branches/initialize_server.html"
    slug_field = "slug"
    slug_url_kwarg = "server"

    def __init__(self, *args, **kwargs):
        self.object = None
        super(InitializeServerView, self).__init__(*args, **kwargs)

    def get_form(self):
        server = self.get_object()
        form = self.form_class(server, self.request.POST or None, 
            initial=self.get_initial(),
            instance=server)
        return form

    def get_success_url(self):
        return reverse("branches:server-log", kwargs=dict(pk=self.get_object().pk))

    def get_initial(self):
        server = self.get_object()
        return {
            "address" : server.address,
            "port" : server.port,
        }

    def form_valid(self, form):
        server = form.save()
        # Get the uername and password and try to connect
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        server.initialize(username, password)
        return redirect(
            "branches:server-initializing",
            owner=server.owner.username,
            project=server.project.slug,
            server=server.slug)


class ServerInitiailizingView(DetailView):
    model = Server
    template_name = "branches/initializing_server.html"
    slug_field = "slug"
    slug_url_kwarg = "server"

    def get(self, *args, **kwargs):
        server = self.get_object()
        if server.initialized:
            return redirect(server.get_absolute_url())
        return super(ServerInitiailizingView, self).get(*args, **kwargs)

class ServerDetailView(DetailView):

    model = Server
    context_object_name = "server"
    slug_field = "slug"
    slug_url_kwarg = "server"

class ServerLogView(DetailView):

    model = Server
    context_object_name = "server"
    template_name = "branches/server_log.html"

class ProjectListView(ListView):

    model = Project
    context_object_name = "project"

    def get_context_data(self, **kwargs):
        ctx = super(ProjectListView, self).get_context_data(**kwargs)
        ctx["page"] = "project-list"
        return ctx


class ProjectDetailView(DetailView):

    model = Project
    context_object_name = "project"
    slug_field = "slug"
    slug_url_kwarg = "project"

class ProjectUpdateView(UpdateView):
    model = Project
    form_class = NewProjectForm

    def get_success_url(self):
        return reverse("branches:project-detail", kwargs=dict(pk=self.get_object().pk))

class ProjectDeleteView(DeleteView):
    model = Project
    template_name = "branches/project_delete.html"

class NewProjectView(CreateView):

    model = Project
    form_class = NewProjectForm

    def get_success_url(self):
        url = self.get_object().get_absolute_url()
        return url

    def get_form_kwargs(self):
        kwargs = super(NewProjectView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs
        

class RackspaceConnectView(FormView):

    form_class = RackspaceConnectForm
    template_name = "branches/rackspace_connect.html"    

    def get(self, request, *args, **kwargs):
        profile = UserProfile.get_profile(self.request.user)
        if profile.rackspace_username and profile.rackspace_api_key:
            return redirect("branches:rackspace-server-list")
        return super(RackspaceConnectView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        api_key = cleaned_data.get("api_key")
        username = cleaned_data.get("username")
        profile = UserProfile.get_profile(self.request.user)
        profile.rackspace_username = username
        profile.rackspace_api_key = api_key
        profile.save()
        return redirect("branches:rackspace-server-list")


class RackspaceServerListView(ListView):

    context_object_name = "servers"
    template_name = "branches/rackspace_server_list.html"

    def get_queryset(self):
        pyrax.set_setting("identity_type", "rackspace")
        profile = UserProfile.get_profile(self.request.user)
        username = profile.rackspace_username
        api_key = profile.rackspace_api_key
        pyrax.set_credentials(username, api_key)
        return pyrax.cloudservers.list()

    def post(self, request, *args, **kwargs):
        data = request.POST
        server_ids = data.getlist("server")
        servers = [server for server in self.get_queryset() if server.id in server_ids]
        for server in servers:
            address = server.networks.get("public")[0]
            Server.objects.create(name=server.name, address=address)
        return redirect("branches:server-list")



class DigitalOceanConnectView(RedirectView):

    def get_oauth(self):
        client_id = settings.DIGITAL_OCEAN_CLIENT_ID
        client_secret = settings.DIGITAL_OCEAN_CLIENT_SECRET
        redirect_uri = "%s%s" % (
            settings.SITE_URL, reverse("branches:digitalocean-authorize"))
        scope = ["read"]
        oauth = OAuth2Session(
            client_id, 
            redirect_uri=redirect_uri,
            scope=scope)        
        return oauth

    def get_redirect_url(self, *args, **kwargs):
        url = "https://cloud.digitalocean.com/v1/oauth/authorize"
        oauth = self.get_oauth()
        authorization_url, state = oauth.authorization_url(
            url)
        print("Authorization url is: %s" % authorization_url)
        return authorization_url

class DigitalOceanAuthorizeView(DigitalOceanConnectView):

    def get_redirect_url(self, *args, **kwargs):
        print(self.request.GET)
        data = self.request.GET
        code = data.get("code")
        oauth = self.get_oauth()

branches/templates/branches/dashboard.html
{% extends "branches/base_site.html" %}
{% block extra_css %}
<link href="/static/css/dashboard.css" rel="stylesheet">
{% endblock extra_css %}


{% block body_classes %}dashboard{% endblock body_classes %}
{% block jumbotron %}{% endblock jumbotron %}
{% block navigation %}
    <div class="container-fluid main-menu">
        <div class="row">
            <div class="col-xs-1 col-sm-1 col-md-2 brand">
                <span class="hidden-xs hidden-sm">
                    <a href="{% url 'home' %}">
                        <b>DEV</b>BRANCH
                    </a>
                </span>
            </div>
            <div class="col-xs-11 col-sm-11 col-md-10 status">
                <div class="profile pull-right">
                    <img src="{{ user.profile.gravatar_url }}" class="img-responsive img-circle pull-right" alt="" width="50px">
                    <div class="name">
                        <span>
                            {{ user.username }}
                        </span>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock navigation %}
{% block content_wrapper %}
    <div class="container-fluid content-wrapper">
        <div class="row">
            <div class="col-xs-1 col-sm-1 col-md-2 sidebar affix">
                <span class="caption hidden-xs hidden-sm">Main Menu</span>
                <div class="menu-item {% if page == 'home' %}active{% endif %}">
                    <a href="{% url 'home' %}"><i class="fa fa-bars"></i>
                        <span class="hidden-xs hidden-sm">Dashboard</span>
                    </a>
                </div>
                <div class="menu-item {% if page == 'project-list' %}active{% endif %}">
                    <a href="{% url 'branches:project-list' %}"><i class="fa fa-github"></i>
                        <span class="hidden-xs hidden-sm">Projects</span>
                    </a>
                </div>
            </div>
            <div class="col-xs-11 col-xs-offset-1 col-sm-11 col-sm-offset-1 col-md-10 col-md-offset-2 main">
                <div class="page-heading">
                    <h2>{% block page_title %}Dashboard{% endblock page_title %}</h2>
                </div>
                <div class="page-subheading">
                    <span>{% block page_subtitle %}{% endblock page_subtitle %}</span>
                </div>
                {% block content %}
                    <div class="container-fluid">
                        <div class="row">
                                <!-- add a server link -->
                            <div class="col-sm-12 col-md-6 col-lg-4">
                                <div class="panel panel-default dashboard-panel">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Add a new server</h3>
                                        <span class="panel-icon">
                                            <i class="fa fa-desktop"></i>                                                
                                        </span>
                                    </div>
                                    <div class="panel-body">
                                        Connect to a server so we can start managing your projects.
                                        <br>
                                        <a href="{% url 'branches:new-server' %}">
                                            <button type="button" class="btn btn-success">Add Server</button>
                                        </a>
                                    </div>
                                </div>
                            </div> <!-- end of add server ad -->
                            
                            <!-- Rackspace import -->
                            <div class="col-sm-12 col-md-6 col-lg-4">
                                <div class="panel panel-default dashboard-panel dashboard-panel-orange">
                                    <div class="panel-heading">
                                        <img src="/static/img/rackspace.png"  width="60px" alt="">
                                        <h3 class="panel-title">Import from Rackspace</h3>
                                    </div>
                                    <div class="panel-body">
                                        Got servers in Rackspace? Import them in one click!
                                        <br>
                                        <a href="{% url 'branches:rackspace-connect' %}">
                                            <button type="button" class="btn btn-danger">Connect to Rackspace</button>
                                        </a>
                                    </div>
                                </div>
                            </div> <!-- end of rackspace import blurb -->

                            <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
                                <div class="panel panel-default dashboard-panel dashboard-panel-blue">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Import from DigitalOcean</h3>
                                    </div>
                                    <div class="panel-body">
                                        Yup... importing from DigitalOcean is a snap too.
                                        <a href="{% url 'branches:digitalocean-connect' %}">
                                            <button type="button" class="btn btn-info">Connect to DigitalOcean</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- end of ads row (add server, rackspace, Do) -->



                    </div>

                {% endblock content %}
            </div>
        </div>
    </div>
{% endblock content_wrapper %}

branches/templates/branches/home.html
{% extends "branches/base_site.html" %}

{% block jumbotron %}
  <div class="jumbotron page-heading site-promotion">
    <div class="container">
      <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-lg-offset-3 manage">
          Manage your server <u>branches</u> remotely
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-lg-offset-4 commands">
          $ git fetch<br>
          $ git pull<br>
          $ git branch another_branch<br>
          <br>
          $ sh run_some_script.sh<br>
        </div>
      </div>

    </div>      
  </div>
{% endblock jumbotron %}


{% block content %}
<div class="features">
  <div class="row">
    <div class="feature pull-left">
      <img src="/static/img/codefork.png" class="pull-left">
      <div class="feature-description pull-left">
        <span class="caption">Perform git operations with a breeze</span>
        <span class="sub-caption">
          git pull, git branch, git log
        </span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="feature pull-right">
      <img src="/static/img/console.png" alt="" class="pull-right">
      <div class="feature-description pull-right">
        <span class="caption">Run custom commands on your server</span>
        <span class="sub-caption">
          Run anything your server supports
        </span>
      </div>      
    </div>
  </div>
</div>
{% endblock content %}

branches/templates/branches/project_detail.html
{% extends "branches/dashboard.html" %}
{% load project_tags %}

{% block page_title %}
    <a href="{% url 'branches:owner-project-list' owner=owner %}" class="back-link">
        <i class="fa fa-chevron-left"></i>
    </a>

    Project {{ project.repository.name }}
{% endblock page_title %}

{% block content %}
    <div class="page-actions">
        <a href="{% url 'branches:project-edit' owner=project.owner project=project.slug %}" class="pull-right"><button class="btn btn-normal">Edit</button></a>
        <a href="{% url 'branches:project-delete' owner=project.owner project=project.slug %}" class="pull-right"><button class="btn btn-normal">Delete</button></a>
    </div>
    {% render_project project full=True %}
{% endblock content %}

branches/templates/branches/project_panel.html
{% load crispy_forms_tags %}

<div class="panel panel-default">
      <div class="panel-heading">

            <h2 class="panel-title">
                <i class="fa fa-github"></i>
                &nbsp;
                <a href="{% if full %}#{% else %}{% url 'branches:project-detail' project=project.slug owner=project.owner.username %}{% endif %}">{{ project.name }}</a>
            </h2>
      </div>
      <div class="panel-body">
            {% for server in project.servers.all %}
                <div class="server" id="server-{{ server.pk }}">
                    <div class="server-header">
                        <h3>
                            <i class="fa fa-desktop"></i>&nbsp;
                            <a href="{% url 'branches:server-detail' owner=server.owner.username project=server.project.slug server=server.slug %}">{{ server.name }}</a>
                        </h3>
                        <span class="server-branch-information">Currently on 
                            <span class="branch-name">
                                <i class="fa fa-code-fork"></i> master
                            </span>
                        </span>
                    </div>



                    {% if show_commits %}
                        <div class="commit-list">
                            <span class="faded-text" data-bind="visible: !statusLoaded">
                                <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading commits...
                            </span>
                            <div data-bind="foreach: commits">
                                <div class="commit">
                                    <img data-bind="attr: { src: gravatar_url}" alt="" class="gravatar img-circle">
                                    <span class="message" data-bind="text: subject"></span>
                                    <span class="author" data-bind="text: author_name"></span>  
                            </div>
                            </div>
                        </div>
                    {% endif %}

                </div>
            {% empty %}
            No servers added yet. <a href="{% url 'branches:new-server' %}">Add a server</a>.
           {% endfor %}


      </div>
</div>

branches/templates/branches/server_detail.html
{% extends "branches/dashboard.html" %}
{% load server_tags %}

{% block page_title %}
    <a href="{% url 'branches:project-detail' owner=server.project.owner project=server.project.slug %}" class="back-link">
        <i class="fa fa-chevron-left"></i>
    </a>
    <i class="fa fa-desktop"></i>&nbsp;&nbsp;{{ server.name }}
{% endblock page_title %}

{% block content %}
    <div class="page-actions">
        <a href="{% url 'branches:server-edit' owner=server.owner.username project=server.project.slug server=server.slug %}" class="pull-right"><button class="btn btn-normal btn-circle"><i class="fa fa-pencil"></i></button></a>
        <a href="{% url 'branches:server-delete' owner=server.owner.username project=server.project.slug server=server.slug %}" class="pull-right"><button class="btn btn-normal btn-circle"><i class="fa fa-trash"></i></button></a>
    </div>

    {% render_server server full=True %}

{% endblock content %}

{% block extra_scripts %}
    <script data-main="/static/js/server-detail" src="/static/js/require.min.js"></script>
<script>
</script>

{% endblock extra_scripts %}

branches/templates/branches/server_list.html
{% extends "branches/dashboard.html" %}
{% load server_tags %}

{% block page_title %}
<a href="{% url 'dashboard' username=username %}" class="back-link">
    <i class="fa fa-chevron-left"></i>
</a>

<i class="fa fa-desktop"></i>
Servers{% endblock page_title %}

{% block content %}

<div class="page-actions">
	<a href="{% url 'branches:new-server' username=username %}" class="pull-right"><button class="btn btn-normal">Add server</button></a>
</div>

{% for server in object_list %}
	{% if forloop.first %}
		<div class="row">
	{% endif %}

	<div class="col-sm-4 col-md-4 col-lg-4">
		{% render_server server %}
	</div>

	{% if forloop.counter|divisibleby:3 %}
		</div>
		<div class="row">
	{% endif %}

	{% if forloop.last %}
		</div>
	{% endif %}
{% empty %}
No servers yet.
{% endfor %}
{% endblock content %}

branches/templates/branches/server_panel.html
{% load crispy_forms_tags %}

<div class="panel panel-default">
      <div class="panel-heading">
            {% include "branches/partials/server/server_status_label.html" %}
            <h2 class="panel-title">
                <i class="fa fa-desktop"></i>
                &nbsp;&nbsp;
                <a href="{{ server.get_absolute_url }}">{{ server.name }}</a>
                <span class="server-address">at {{ server.address }}</span>
            </h2>

            {% if show_actions %}
                <div class="actions">
                    <a class="btn btn-small btn-default" href="{% url 'branches:server-edit' owner=server.owner.username project=server.project.slug server=server.slug %}">Edit</a>
                    <a class="btn btn-small btn-danger" href="{% url 'branches:server-delete' owner=server.owner.username project=server.project.slug server=server.slug %}">Delete</a>
                </div>
            {% endif %}

      </div>
      <div class="panel-body">

            {% if server.initialized %}
            <div class="server {% if full %}full{% endif %}" id="server-{{ server.slug }}">

                <div class="branch-change-div">
                    {% if full %}
                        {% crispy change_branch_form %}

                        <div class="branch-select-actions" data-bind="visible: !changingBranches() && dataLoaded()">
                            <!-- ko if: updatingBranches() -->
                                Refreshing...
                            <!-- /ko -->
                            <!-- ko if: !updatingBranches() -->
                                <a href="javscript:void(0)" data-bind="click: updateBranchList">Refresh</a>
                            <!-- /ko -->
                        </div>

                        <div class="branch-actions" data-bind="visible: changingBranches() || canChangeBranch() || changeBranchLog()">
                            <!-- ko if: canChangeBranch() -->
                                <span class="explanation">
                                    Change branch from <span class="branch-name"><i class="fa fa-code-fork"></i>&nbsp;<span data-bind="html: currentBranch"></span></span> to
                                    <span class="branch-name"><i class="fa fa-code-fork"></i>&nbsp;<span data-bind="html: selectedBranch"></span></span>?
                                </span>
                                <button type="button" class="btn btn-small btn-danger" data-bind="click: changeBranch">Change</button>
                                <button type="button" class="btn btn-small btn-default" data-bind="click: resetSelectedBranch">Cancel</button>
                            <!-- /ko -->
                            <!-- ko if: changingBranches() -->
                                <span class="explanation">
                                    <i class="fa fa-spin fa-spinner"></i>
                                    &nbsp;&nbsp;Changing branch to 
                                    <span class="branch-name"><i class="fa fa-code-fork"></i>&nbsp;<span data-bind="html: selectedBranch"></span></span>
                                </span>
                                <button type="button" class="btn btn-small btn-danger" data-bind="click: cancelChangeBranch">Cancel</button>
                            <!-- /ko -->
        
                            <!-- ko if: changeBranchLog -->                        
                                <div class="branch-change-log" data-bind="html: changeBranchLog()"></div>
                                <a data-bind="attr: { href: '/branches/api/v1/change-branch-request/' + changeBranchRequest() + '/log/'}" target="_blank">View Log</a>
                            <!-- /ko -->
                        </div>
                    {% else %}
                    <div class="current-branch" data-bind="visible: dataLoaded()">
                        On branch <span class="branch-name"><i class="fa fa-code-fork"></i>&nbsp;<span data-bind="html: currentBranch"></span>
                    </div>
                    {% endif %}

                    <span class="faded-text" data-bind="visible: !dataLoaded()">
                        <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading branch...
                    </span>
                </div>


                {% if full %}
                    <div class="commit-list">
                        <span class="faded-text" data-bind="visible: !dataLoaded()">
                            <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading commits...
                        </span>
                        <div data-bind="foreach: commits">
                            <div class="commit">
                                <img data-bind="attr: { src: gravatar_url}" alt="" class="gravatar img-circle">
                                <span class="message" data-bind="text: subject"></span>
                                <span class="author" data-bind="text: author_name"></span>  
                        </div>
                        </div>
                    </div>
                {% endif %}

            </div>
            {% else %}
                We haven't established a connection to this server yet. <a href="{% url 'branches:initialize-server' owner=server.owner.username project=server.project.slug server=server.slug %}">Initialize</a>.
            {% endif %}
      </div>
</div>